kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: mi-uat-build
  namespace: common-svc
  labels:
    app.kubernetes.io/name: mi-uat-build
spec:
  output:
    to:
      kind: DockerImage
      name: 'image-registry.openshift-image-registry.svc:5000/common-svc/wso2mi:imagetag'
    pushSecret:
      name: nexus
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: integration-patform-dev
        name: 'wso2mi:4.2.0.0'
      dockerfilePath: Dockerfile
  source:
    type: Binary
    binary: {}
